--initial database
CREATE DATABASE postgrelearning;

DROP DATABASE postgrelearning;

--testing template
CREATE DATABASE templatetest WITH TEMPLATE postgrelearning;

DROP DATABASE templatetest;

DROP DATABASE IF EXISTS templatetest;

DROP DATABASE IF EXISTS templatetest WITH FORCE;


--create table
CREATE TABLE TableTest1 
    (ID int NOT NULL, 
    SomeValue varchar(50) NOT NULL, 
    AnotherValue varchar(30) NULL);



CREATE SCHEMA hsr;


CREATE TABLE hsr.radiobrand 
    (radiobrandid int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    radiobranddesc varchar(50) NOT NULL);

CREATE TABLE hsr.radio
    (radioid int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    radioname varchar(50) NOT NULL,
    radiobrandid int REFERENCES hsr.RadioBrand NOT NULL);


DROP TABLE hsr.radiobrand
DROP TABLE hsr.radio



CREATE TABLE hsr.radio
    (radioid int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    radioname varchar(50) NOT NULL,
    radiobrandid int NOT NULL,
    CONSTRAINT radiopk PRIMARY KEY (radioid),
    FOREIGN KEY (radiobrandid) REFERENCES hsr.RadioBrand(radiobrandid));



insert into hsr.radiobrand
(radiobranddesc)
VALUES
('Icom');

SELECT radiobrandid,
    radiobranddesc
FROM hsr.radiobrand;