--create a schema
CREATE SCHEMA sales;

--show the search path for schemas
SHOW search_path;

--modify the search path
SET search_path TO sales,public;


--create a table with defaults and calculated column
CREATE TABLE sales.saledetail
(saledetailid int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
saledatetime TIMESTAMP DEFAULT NOW(),
itemtotal MONEY,
itemdiscount NUMERIC(2,2),
saletotal MONEY GENERATED ALWAYS AS (itemtotal * itemdiscount) STORED,
CONSTRAINT saledetailpk PRIMARY KEY (saledetailid));

-- add data to the table
INSERT INTO sales.saledetail
(itemtotal,itemdiscount)
VALUES
(343.42,.95);

-- retrieve the data
SELECT * FROM sales.saledetail;

--experimenting with structures
TRUNCATE sales.saledetail;
DROP TABLE sales.saledetail;

--inherit from the salesdetail table
CREATE TABLE sales.specialsale
(promodesc VARCHAR(50))
INHERITS (sales.saledetail);

--this will fail
INSERT INTO sales.specialsale
(itemtotal,itemdiscount,promodesc)
VALUES
(299.99,.92,'Winter Field Day');

--remove the inherited table
DROP TABLE sales.specialsale;

--if we created the main table this way, the INSERT above works
CREATE TABLE sales.saledetail
(saledetailid SERIAL,
saledatetime TIMESTAMP DEFAULT NOW(),
itemtotal MONEY,
itemdiscount NUMERIC(2,2),
saletotal MONEY GENERATED ALWAYS AS (itemtotal * itemdiscount) STORED,
CONSTRAINT saledetailpk PRIMARY KEY (saledetailid));


--add a column
ALTER TABLE sales.saledetail ADD COLUMN saledesc VARCHAR(50);

--add a column with safety
ALTER TABLE sales.saledetail ADD COLUMN IF NOT EXISTS saledesc VARCHAR(50);


--remove a column
ALTER TABLE sales.saledetail DROP COLUMN saledesc;

--remove a column with safety
ALTER TABLE sales.saledetail DROP COLUMN IF EXISTS saledesc;



--add a check constraint
ALTER TABLE sales.saledetail ADD CHECK (itemtotal > '0');

